# -*- coding: utf-8 -*-
"""pitchpredict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Gw0mRAxWOvHn202gN9aHhd-FzuDubxU
"""

!pip install optuna

import warnings
import optuna
from optuna.samplers import TPESampler
from sklearn.model_selection import KFold
from sklearn.base import clone
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.metrics import f1_score, accuracy_score, mean_absolute_error
from imblearn.over_sampling import SMOTE
from sklearn.calibration import CalibratedClassifierCV
from sklearn.impute import SimpleImputer
import joblib
from scipy.stats import randint, uniform
from sklearn.model_selection import PredefinedSplit

warnings.filterwarnings("ignore", category=FutureWarning)

# -------------------- Constants & Helper Functions -------------------- #
TEAM_MAPPING = {
    'Man Utd': 'Manchester Utd', 'Man United': 'Manchester Utd',
    'Man City': 'Manchester City', 'Newcastle Utd': 'Newcastle United',
    'Newcastle Ut': 'Newcastle United', "Nott'ham Forest": 'Nottingham Forest',
    'Paris S-G': 'Paris Saint-Germain', 'Inter Milan': 'Inter',
    'Spurs': 'Tottenham', 'West Ham Utd': 'West Ham United'
}

def clean_numeric_values(value):
    if isinstance(value, str):
        cleaned = value.replace(',', '').replace(' ', '')
        if cleaned.replace('.', '', 1).isdigit():
            return float(cleaned)
    return value

def standardize_team_names(df, column_name):
    df = df.copy()
    df.loc[:, column_name] = df[column_name].replace(TEAM_MAPPING).str.strip()
    return df

# -------------------- Custom Group K-Fold Splitter -------------------- #
class TeamBasedGroupKFold:
    def __init__(self, n_splits=5, random_state=None):
        self.n_splits = n_splits
        self.random_state = random_state

    def split(self, fixtures_df):
        unique_teams = pd.concat([fixtures_df['Home_Team'], fixtures_df['Away_Team']]).unique()
        kf = KFold(n_splits=self.n_splits, shuffle=True, random_state=self.random_state)

        for _, test_teams_idx in kf.split(unique_teams):
            test_teams = unique_teams[test_teams_idx]
            val_mask = fixtures_df['Home_Team'].isin(test_teams) | fixtures_df['Away_Team'].isin(test_teams)
            train_idx = fixtures_df.index[~val_mask].values
            val_idx = fixtures_df.index[val_mask].values
            yield train_idx, val_idx

# -------------------- Data Loading & Preprocessing -------------------- #
def load_and_preprocess_data():
    stats_df = pd.read_csv('/content/Combined_Leagues_Stats.csv').copy()
    fixtures_df = pd.read_csv('/content/Fixture_Results.csv').copy()

    numeric_cols = [
        'progressive_carries', 'progressive_passes', 'xg', 'npxg',
        'xg_assist', 'npxg_xg_assist', 'goals_per90', 'assists_per90',
        'goals_assists_per90', 'goals_pens_per90', 'xg_per90',
        'xg_assist_per90', 'npxg_per90', 'Home_xG', 'Away_xG'
    ]

    for df in [stats_df, fixtures_df]:
        for col in numeric_cols:
            if col in df.columns:
                df.loc[:, col] = df[col].apply(clean_numeric_values)

    # Reset index after dropping rows
    fixtures_df = fixtures_df.dropna(subset=['Home_xG', 'Away_xG']).copy()
    fixtures_df.reset_index(drop=True, inplace=True)  # <-- FIX 1

    stats_df = standardize_team_names(stats_df, 'team')
    fixtures_df = standardize_team_names(fixtures_df, 'Home_Team')
    fixtures_df = standardize_team_names(fixtures_df, 'Away_Team')

    # Reset index after filtering
    fixtures_df = fixtures_df.loc[fixtures_df['Home_Team'] != fixtures_df['Away_Team']].copy()
    fixtures_df.reset_index(drop=True, inplace=True)  # <-- FIX 2

    stats_df.loc[:, 'total_progression'] = (
        stats_df['progressive_carries'] + stats_df['progressive_passes']
    )

    feature_columns = [
        'total_progression', 'goals_per90', 'assists_per90',
        'goals_assists_per90', 'goals_pens_per90', 'xg_per90',
        'xg_assist_per90', 'npxg_per90'
    ]

    imputer = SimpleImputer(strategy='median')
    stats_df.loc[:, feature_columns] = imputer.fit_transform(stats_df[feature_columns])

    team_stats = stats_df.set_index('team')[feature_columns].to_dict('index')

    return team_stats, fixtures_df, feature_columns

# -------------------- TeamBasedGroupKFold Splitter -------------------- #
class TeamBasedGroupKFold:
    def __init__(self, n_splits=5, random_state=None):
        self.n_splits = n_splits
        self.random_state = random_state

    def split(self, fixtures_df):
        unique_teams = pd.concat([fixtures_df['Home_Team'], fixtures_df['Away_Team']]).unique()
        kf = KFold(n_splits=self.n_splits, shuffle=True, random_state=self.random_state)

        for _, test_teams_idx in kf.split(unique_teams):
            test_teams = unique_teams[test_teams_idx]
            val_mask = (
                fixtures_df['Home_Team'].isin(test_teams) |
                fixtures_df['Away_Team'].isin(test_teams)
            )
            # Convert boolean mask to positional indices
            val_idx = val_mask.to_numpy().nonzero()[0]  # <-- FIX 3
            train_idx = (~val_mask).to_numpy().nonzero()[0]
            yield train_idx, val_idx
# -------------------- Optuna Objective Function -------------------- #
def create_objective(X_train, y_class_train, y_reg_train):
    def objective(trial):
        params = {
            'booster': trial.suggest_categorical('booster', ['gbtree', 'dart']),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
            'n_estimators': trial.suggest_int('n_estimators', 100, 500),
            'max_depth': trial.suggest_int('max_depth', 3, 12),
            'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
            'gamma': trial.suggest_float('gamma', 0, 0.5),
            'subsample': trial.suggest_float('subsample', 0.5, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
            'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 1.0),
            'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 1.0),
            'objective': 'multi:softprob',
            'num_class': 3,
            'random_state': 42,
            'eval_metric': 'mlogloss',
            'early_stopping_rounds': 20  # Moved to constructor parameters
        }

        # Handle class imbalance
        class_weights = compute_class_weight('balanced', classes=np.unique(y_class_train), y=y_class_train)

        # Create pipeline with SMOTE
        pipeline = ImbPipeline([
            ('smote', SMOTE(random_state=42)),
            ('clf', xgb.XGBClassifier(**params))
        ])

        # Inner cross-validation
        scores = []
        inner_cv = TeamBasedGroupKFold(n_splits=3, random_state=42)
        for inner_train_idx, inner_val_idx in inner_cv.split(fixtures_df.iloc[train_idx]):
            X_inner_train = X_train[inner_train_idx]
            y_inner_train = y_class_train[inner_train_idx]

            # Apply SMOTE and sample weights
            X_res, y_res = SMOTE(random_state=42).fit_resample(X_inner_train, y_inner_train)
            sample_weights_res = class_weights[y_res]

            # Modified fit call
            pipeline.named_steps['clf'].fit(
                X_res, y_res,
                sample_weight=sample_weights_res,
                eval_set=[(X_train[inner_val_idx], y_class_train[inner_val_idx])],
                verbose=False
            )

            y_pred = pipeline.predict(X_train[inner_val_idx])
            scores.append(f1_score(y_class_train[inner_val_idx], y_pred, average='macro'))

        return np.mean(scores)
    return objective

# -------------------- Training Execution -------------------- #
if __name__ == "__main__":
    team_stats, fixtures_df, feature_columns = load_and_preprocess_data()

    # Feature engineering
    fixtures_df['features'] = fixtures_df.apply(
        lambda row: (
            list(team_stats[row['Home_Team'].strip()].values()) +  # Fixed closing )
            list(team_stats[row['Away_Team'].strip()].values())    # Fixed closing )
        ), axis=1
    )

    fixtures_df['result'] = fixtures_df.apply(
        lambda row: 2 if row['Home_Score'] > row['Away_Score'] else 1 if row['Home_Score'] == row['Away_Score'] else 0,
        axis=1
    )

    X = np.array(fixtures_df['features'].tolist())
    y_class = fixtures_df['result'].values
    y_reg = fixtures_df[['Home_xG', 'Away_xG']].values

    group_kfold = TeamBasedGroupKFold(n_splits=5, random_state=42)

    for fold, (train_idx, val_idx) in enumerate(group_kfold.split(fixtures_df)):
        X_train, X_val = X[train_idx], X[val_idx]
        y_class_train, y_class_val = y_class[train_idx], y_class[val_idx]
        y_reg_train, y_reg_val = y_reg[train_idx], y_reg[val_idx]

        # Corrected Optuna optimization call
        study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))
        study.optimize(
            create_objective(X_train, y_class_train, y_reg_train),
            n_trials=50
        )

        best_params = study.best_params

        # Now use best_params
        # Instantiate classifier with early stopping and eval_metric in the constructor
        clf = xgb.XGBClassifier(
            **best_params,
            early_stopping_rounds=20,
            eval_metric="mlogloss"
        )

        # ======== CRITICAL FIX ========
        # 1. Apply SMOTE to training data
        smote = SMOTE(random_state=42)
        X_res, y_res = smote.fit_resample(X_train, y_class_train)
        # ==============================

        # 2. Train classifier with early stopping (parameters passed in constructor)
        clf.fit(
            X_res, y_res,
            eval_set=[(X_val, y_class_val)],
            # early_stopping_rounds=20, # REMOVE - passed in constructor
            verbose=False
            # eval_metric="mlogloss" # REMOVE - passed in constructor
        )

        # 3. Create a clean classifier copy without early stopping for calibration
        # Early stopping should not be used during calibration fit
        calib_clf_params = {k: v for k, v in best_params.items() if k not in ['early_stopping_rounds', 'eval_metric']}
        calib_clf = xgb.XGBClassifier(**calib_clf_params)
        calib_clf.fit(X_res, y_res) # Train on SMOTE data without early stopping parameters

        # 4. Calibrate using original training splits
        calibrated_clf = CalibratedClassifierCV(
            calib_clf,
            method='sigmoid',
            cv=KFold(n_splits=5, shuffle=True, random_state=42)
        )
        calibrated_clf.fit(X_train, y_class_train)

        # 5. Train regression models - Use best_params, early stopping and eval_metric usually not needed for regressor fit unless you specifically want it.
        reg_home_params = {k: v for k, v in best_params.items() if k not in ['objective', 'num_class', 'eval_metric', 'early_stopping_rounds']}
        reg_away_params = {k: v for k, v in best_params.items() if k not in ['objective', 'num_class', 'eval_metric', 'early_stopping_rounds']}

        # Note: Resampling y_reg_train for regression needs care.
        # A simple modulo can work if the resampling preserves order, but it's potentially fragile.
        # A safer approach might be to use the original y_reg_train and handle sample weights if needed,
        # or ensure the resampling method handles multi-output targets correctly.
        # For now, keeping the original logic but noting this is a potential area for refinement.
        y_reg_train_res = y_reg_train[np.arange(len(X_res)) % len(y_reg_train)]

        reg_home = xgb.XGBRegressor(**reg_home_params).fit(X_res, y_reg_train_res[:, 0])
        reg_away = xgb.XGBRegressor(**reg_away_params).fit(X_res, y_reg_train_res[:, 1])

        # Save model artifacts
        joblib.dump({
            'classifier': calibrated_clf,
            'regressor_home': reg_home,
            'regressor_away': reg_away,
            'feature_columns': feature_columns,
            'team_stats': team_stats,
            'best_params': best_params
        }, f'xgb_model_fold{fold+1}.pkl')

        # Validation metrics
        print(f"\nFold {fold+1} Metrics:")
        print(f"Val Accuracy: {accuracy_score(y_class_val, calibrated_clf.predict(X_val)):.4f}")
        print(f"Val F1: {f1_score(y_class_val, calibrated_clf.predict(X_val), average='macro'):.4f}")

    joblib.dump({
        'team_stats': team_stats,
        'feature_columns': feature_columns
    }, 'xgb_artifacts.pkl')

# -------------------- Ensemble Prediction Function -------------------- #
def predict_fixtures(fixtures_csv_path):
    artifacts = joblib.load('xgb_artifacts.pkl')
    team_stats = artifacts['team_stats']
    feature_columns = artifacts['feature_columns']

    # Load all fold models
    models = [joblib.load(f'xgb_model_fold{i+1}.pkl') for i in range(5)]

    # Prepare new fixtures
    new_fixtures = pd.read_csv(fixtures_csv_path)
    new_fixtures = standardize_team_names(new_fixtures, 'Home_Team')
    new_fixtures = standardize_team_names(new_fixtures, 'Away_Team')

    new_fixtures['features'] = new_fixtures.apply(
            lambda row: (
                list(team_stats[row['Home_Team'].strip()].values()) +  # Fixed closing )
                list(team_stats[row['Away_Team'].strip()].values())    # Fixed closing )
            ), axis=1
        )
    X_new = np.array(new_fixtures['features'].tolist())

    # Ensemble predictions
    class_probs = np.zeros((X_new.shape[0], 3))
    home_xg = np.zeros(X_new.shape[0])
    away_xg = np.zeros(X_new.shape[0])

    for model in models:
        class_probs += model['classifier'].predict_proba(X_new)
        home_xg += model['regressor_home'].predict(X_new)
        away_xg += model['regressor_away'].predict(X_new)

    result_df = pd.DataFrame({
        'Home_Team': new_fixtures['Home_Team'],
        'Away_Team': new_fixtures['Away_Team'],
        'Home_Win_Prob': class_probs[:, 2] / len(models),
        'Draw_Prob': class_probs[:, 1] / len(models),
        'Away_Win_Prob': class_probs[:, 0] / len(models),
        'Predicted_Home_xG': home_xg / len(models),
        'Predicted_Away_xG': away_xg / len(models)
    })

    # Add calculated columns
    result_df['Total_Goals'] = (np.round(result_df['Predicted_Home_xG']) +
                              np.round(result_df['Predicted_Away_xG']))
    result_df['Prob_Diff'] = abs(result_df['Home_Win_Prob'] - result_df['Away_Win_Prob'])

    # Sort by probability difference
    result_df = result_df.sort_values('Prob_Diff', ascending=False)

    return result_df

predictions = predict_fixtures('fixtures.csv')

predictions

